### PR TITLE
updating googlefonts profile codetests

### PR DESCRIPTION
**Pull request by felipesanches**

### CODE REVIEW

**Comment by felipesanches** [comment]
@simoncozens, I think fontspector still does not support check overrides, right?

image

**Comment by felipesanches** [comment]
For now, on the fontbakery repo, I'll split-out these tests to a file dedicated to testing check overrides:  `tests/test_checks_googlefonts_overrides.py`

And then fontspector can copy that file once check-overriding support is implemented.

**Comment by simoncozens** [comment]
Very nice, thank you!

**Comment by felipesanches** [comment]
Corresponding changes made at https://github.com/fonttools/fontbakery/pull/4888/commits/7852a669736a060514b1bcd56615473e8ed949cf

**Pull request merged**
